name: Site Published

on:
  page_build:  
  workflow_dispatch:
    # manual run

jobs:
  ping:
    name: Ping Google
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request
        run: curl https://www.google.com/ping?sitemap=https://aybe.org/sitemap.xml